### ISSUE TITLE
Mac supports?

### ISSUE THREAD

**Issue by jazzman31** [KaixoCode/Mixijo#2]
I tried on Mac(Apple Silicon) but it didn't work.... also it's buggy on Windows.
Do you have any new version?
Thanks
Jean

**Comment by KaixoCode** [comment]
There are no plans for Mac support. And what exactly is the problem on Windows? I've been using it myself every day without a problem.

**Comment by jazzman31** [comment]
When I load it the mixer doesn't have any GUI. I've tried with 2 different PCs and getting the same result.
Please below result:
[Mixijo] 2023-01-28 23:53:37 [log] loading theme...
[Mixijo] 2023-01-28 23:53:37 [log] loaded theme
[Mixijo] 2023-01-28 23:53:37 [err] No audio device found with the name (Speakers)
[Mixijo] 2023-01-28 23:53:37 [log] available audio devices:
[Mixijo] 2023-01-28 23:53:37 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:53:37 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:53:37 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:53:37 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:53:37 [log] loading theme...
[Mixijo] 2023-01-28 23:53:37 [log] loaded theme
[Mixijo] 2023-01-28 23:53:44 [log] Reloading settings...
[Mixijo] 2023-01-28 23:53:44 [log] loading theme...
[Mixijo] 2023-01-28 23:53:44 [log] loaded theme
[Mixijo] 2023-01-28 23:53:44 [log] Reloaded settings
[Mixijo] 2023-01-28 23:53:46 [log] Opening ASIO Control Panel
[Mixijo] 2023-01-28 23:53:48 [log] Reloading settings...
[Mixijo] 2023-01-28 23:53:48 [log] loading theme...
[Mixijo] 2023-01-28 23:53:48 [log] loaded theme
[Mixijo] 2023-01-28 23:53:48 [log] Reloaded settings
[Mixijo] 2023-01-28 23:53:49 [log] Reloading settings...
[Mixijo] 2023-01-28 23:53:49 [log] loading theme...
[Mixijo] 2023-01-28 23:53:49 [log] loaded theme
[Mixijo] 2023-01-28 23:53:49 [log] Reloaded settings
[Mixijo] 2023-01-28 23:53:49 [log] Reloading settings...
[Mixijo] 2023-01-28 23:53:49 [log] loading theme...
[Mixijo] 2023-01-28 23:53:49 [log] loaded theme
[Mixijo] 2023-01-28 23:53:49 [log] Reloaded settings
[Mixijo] 2023-01-28 23:53:49 [log] Reloading settings...
[Mixijo] 2023-01-28 23:53:49 [log] loading theme...
[Mixijo] 2023-01-28 23:53:49 [log] loaded theme
[Mixijo] 2023-01-28 23:53:49 [log] Reloaded settings
[Mixijo] 2023-01-28 23:53:49 [log] Reloading settings...
[Mixijo] 2023-01-28 23:53:49 [log] loading theme...
[Mixijo] 2023-01-28 23:53:49 [log] loaded theme
[Mixijo] 2023-01-28 23:53:49 [log] Reloaded settings
[Mixijo] 2023-01-28 23:53:51 [log] ===========================================
[Mixijo] 2023-01-28 23:53:51 [log]                Information                 
[Mixijo] 2023-01-28 23:53:51 [log] ===========================================
[Mixijo] 2023-01-28 23:53:51 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:53:51 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:53:51 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:53:51 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:53:51 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:53:51 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:53:51 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:53:51 [log] buffersize: 256
[Mixijo] 2023-01-28 23:53:51 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:53:51 [log] ===========================================
[Mixijo] 2023-01-28 23:54:26 [log] ===========================================
[Mixijo] 2023-01-28 23:54:26 [log]                Information                 
[Mixijo] 2023-01-28 23:54:26 [log] ===========================================
[Mixijo] 2023-01-28 23:54:26 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:54:26 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:54:26 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:54:26 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:54:26 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:54:26 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:54:26 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:54:26 [log] buffersize: 256
[Mixijo] 2023-01-28 23:54:26 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:54:26 [log] ===========================================
[Mixijo] 2023-01-28 23:54:28 [log] ===========================================
[Mixijo] 2023-01-28 23:54:28 [log]                Information                 
[Mixijo] 2023-01-28 23:54:28 [log] ===========================================
[Mixijo] 2023-01-28 23:54:28 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:54:28 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:54:28 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:54:28 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:54:28 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:54:28 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:54:28 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:54:28 [log] buffersize: 256
[Mixijo] 2023-01-28 23:54:28 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:54:28 [log] ===========================================
[Mixijo] 2023-01-28 23:54:30 [log] Opening ASIO Control Panel
[Mixijo] 2023-01-28 23:54:45 [log] ===========================================
[Mixijo] 2023-01-28 23:54:45 [log]                Information                 
[Mixijo] 2023-01-28 23:54:45 [log] ===========================================
[Mixijo] 2023-01-28 23:54:45 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:54:45 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:54:45 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:54:45 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:54:45 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:54:45 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:54:45 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:54:45 [log] buffersize: 256
[Mixijo] 2023-01-28 23:54:45 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:54:45 [log] ===========================================
[Mixijo] 2023-01-28 23:54:47 [log] Reloading settings...
[Mixijo] 2023-01-28 23:54:47 [log] loading theme...
[Mixijo] 2023-01-28 23:54:47 [log] loaded theme
[Mixijo] 2023-01-28 23:54:47 [log] Reloaded settings
[Mixijo] 2023-01-28 23:54:53 [log] Opening ASIO Control Panel
[Mixijo] 2023-01-28 23:56:28 [log] Reloading settings and reopening devices...
[Mixijo] 2023-01-28 23:56:28 [log] loading theme...
[Mixijo] 2023-01-28 23:56:28 [log] loaded theme
[Mixijo] 2023-01-28 23:56:28 [err] No audio device found with the name (Speakers)
[Mixijo] 2023-01-28 23:56:28 [log] available audio devices:
[Mixijo] 2023-01-28 23:56:28 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:56:28 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:56:28 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:56:28 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:56:28 [log] loading theme...
[Mixijo] 2023-01-28 23:56:28 [log] loaded theme
[Mixijo] 2023-01-28 23:56:28 [log] Reloaded settings and reopened devices
[Mixijo] 2023-01-28 23:57:35 [log] ===========================================
[Mixijo] 2023-01-28 23:57:35 [log]                Information                 
[Mixijo] 2023-01-28 23:57:35 [log] ===========================================
[Mixijo] 2023-01-28 23:57:35 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:57:35 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:57:35 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:57:35 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:57:35 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:57:35 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:57:35 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:57:35 [log] buffersize: 256
[Mixijo] 2023-01-28 23:57:35 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:57:35 [log] ===========================================
[Mixijo] 2023-01-28 23:57:40 [log] ===========================================
[Mixijo] 2023-01-28 23:57:40 [log]                Information                 
[Mixijo] 2023-01-28 23:57:40 [log] ===========================================
[Mixijo] 2023-01-28 23:57:40 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:57:40 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:57:40 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:57:40 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:57:40 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:57:40 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:57:40 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:57:40 [log] buffersize: 256
[Mixijo] 2023-01-28 23:57:40 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:57:40 [log] ===========================================
[Mixijo] 2023-01-28 23:57:42 [log] ===========================================
[Mixijo] 2023-01-28 23:57:42 [log]                Information                 
[Mixijo] 2023-01-28 23:57:42 [log] ===========================================
[Mixijo] 2023-01-28 23:57:42 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:57:42 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:57:42 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:57:42 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:57:42 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:57:42 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:57:42 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:57:42 [log] buffersize: 256
[Mixijo] 2023-01-28 23:57:42 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:57:42 [log] ===========================================
[Mixijo] 2023-01-28 23:57:43 [log] ===========================================
[Mixijo] 2023-01-28 23:57:43 [log]                Information                 
[Mixijo] 2023-01-28 23:57:43 [log] ===========================================
[Mixijo] 2023-01-28 23:57:43 [log] no audio device opened, available devices:
[Mixijo] 2023-01-28 23:57:43 [log]   ASIO4ALL v2
[Mixijo] 2023-01-28 23:57:43 [log] available midi-in devices:
[Mixijo] 2023-01-28 23:57:43 [log] opened midi-in device: 
[Mixijo] 2023-01-28 23:57:43 [log] available midi-out devices:
[Mixijo] 2023-01-28 23:57:43 [log]   Microsoft GS Wavetable Synth
[Mixijo] 2023-01-28 23:57:43 [log] opened midi-out device: 
[Mixijo] 2023-01-28 23:57:43 [log] buffersize: 256
[Mixijo] 2023-01-28 23:57:43 [log] sampleRate: 44100
[Mixijo] 2023-01-28 23:57:43 [log] ===========================================
[Mixijo] 2023-01-28 23:57:44 [log] Opening ASIO Control Panel
[Mixijo] 2023-01-28 23:58:02 [log] Reloading settings...
[Mixijo] 2023-01-28 23:58:02 [log] loading theme...
[Mixijo] 2023-01-28 23:58:02 [log] loaded theme
[Mixijo] 2023-01-28 23:58:02 [log] Reloaded settings

**Comment by jazzman31** [comment]
OK? I got it! Now I don't have any signal from my web browser...
Am I doing something wrong?
Thank you,
Jean
{
    "audio": "ZenTour SC ASIO Driver",
    "samplerate": 44100,
    "buffersize": 256,
    "midiin": "Microsoft GS Wavetable Synth",
    "midiout": "Microsoft GS Wavetable Synth",
    "buttons": [ ],
    "channels" : {
        "outputs" : [
            { "endpoints" : [ "OUT 1", "Chrome 2" ] , "name" : "Google"},
            { "endpoints" : [ "OUT 2", "Chrome 3" ], "name" : "Chrome", "midimapping" : [ { "cc" : 83, "param" : "gain" } ] },
            { "endpoints" : [ "OUT 1", "OUT 2" ], "name" : "OBS", "midimapping" : [] },
            { "endpoints" : [ "OUT 3", "OUT 4" ], "name" : "3-4", "midimapping" : [ { "cc" : 73, "param" : "gain" } ] },
            { "endpoints" : [ "OUT 1", "OUT 2" ], "name" : "OUTEST", "midimapping" : [ { "cc" : 73, "param" : "gain" } ] }

           
        ],
        "inputs" : [
             { "endpoints" : [ "IN 1" ], "name" : "Microphone" },
             { "endpoints" : [ "IN 2"], "name" : "Chrome A" },
             { "endpoints" : [ "IN 3" ], "name" : "Chrome B" }
        ]
    },
