### ISSUE TITLE
[IDEA] Integrated IR loader

### ISSUE THREAD

**Issue by MarcoRavich** [KaixoCode/Mixijo#3]
Hi there, 1st of all thanks for yor work !

I've added it to the [ASIO section](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Tools.md#asio-) in the [Tools page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Tools.md#--) for the [HyMPS project](https://forart.it/HyMPS): hope you'll check it !

Dunno if the idea falls in the project scope, but nowdays Impulse Responses are pretty wide used (especially in hiend/professional environments), so it would be great to have an integrated system-wide loader.

Hope that inspires.

Thanks in advance.

**Comment by KaixoCode** [comment]
Hey! Thanks for adding it to the HyMPS project! 

I want to keep it as lightweight as possible, so adding IR unfortunately does not fall under the project scope. The idea for Mixijo is that you can run audio between applications, it was specifically designed with [SAR](https://github.com/eiz/SynchronousAudioRouter) in mind. If you need additional features I would assume you'd use a DAW.

There is an improved version of Mixijo in the works, which I'm already using myself, but it's not ready for public usage yet. This new version has a standalone UI that connects to the audio-routing back-end over a websocket. So you can open the UI in the browser, as an Electron app, and even on other devices in the local network. But again, I don't plan on adding any more elaborate features to it, as its main purpose is to simply route audio.

**Comment by MarcoRavich** [comment]
Thanks for the explanation!
